export const AUTH_SIGNIN_ACCOUNT_START = 'AUTH_SIGNIN_ACCOUNT_START';
export const AUTH_SIGNIN_ACCOUNT_SUCCESS = 'AUTH_SIGNIN_ACCOUNT_SUCCESS';
export const AUTH_SIGNIN_ACCOUNT_FAIL = 'AUTH_SIGNIN_ACCOUNT_FAIL';

export const AUTH_UPDATE_ACCOUNT_START = 'AUTH_UPDATE_ACCOUNT_START';
export const AUTH_UPDATE_ACCOUNT_SUCCESS = 'AUTH_UPDATE_ACCOUNT_SUCCESS';
export const AUTH_UPDATE_ACCOUNT_FAIL = 'AUTH_UPDATE_ACCOUNT_FAIL';

export const AUTH_SIGNOUT_START = 'AUTH_SIGNOUT_START';
export const AUTH_SIGNOUT_SUCCESS = 'AUTH_SIGNOUT_SUCCESS';
export const AUTH_SIGNOUT_FAIL = 'AUTH_SIGNOUT_FAIL';
