export const APP_INSTANCE_SYNC_START = 'APP_INSTANCE_SYNC_START';
export const APP_INSTANCE_SYNC_SUCCESS = 'APP_INSTANCE_SYNC_SUCCESS';
export const APP_INSTANCE_SYNC_FAIL = 'APP_INSTANCE_SYNC_FAIL';

// APP ACTION
export const APP_CHECK_START = 'APP_CHECK_START';
export const APP_CHECK_SUCCESS = 'APP_CHECK_SUCCESS';
export const APP_CHECK_FAIL = 'APP_CHECK_FAIL';

// APP LANG ACTION
export const APP_LANG_CHANGE_START = 'APP_LANG_CHANGE_START';
export const APP_LANG_CHANGE_SUCCESS = 'APP_LANG_CHANGE_SUCCESS';
export const APP_LANG_CHANGE_FAIL = 'APP_LANG_CHANGE_FAIL';

// APP SETTINGS
export const APP_SETTINGS_START = 'APP_SETTINGS_START';
export const APP_SETTINGS_SUCCESS = 'APP_SETTINGS_SUCCESS';
export const APP_SETTINGS_FAIL = 'APP_SETTINGS_FAIL';
// APP NETWORK
export const APP_NETWORKS_START = 'APP_NETWORKS_START';
export const APP_NETWORKS_SUCCESS = 'APP_NETWORKS_SUCCESS';
export const APP_NETWORKS_FAIL = 'APP_NETWORKS_FAIL';
